#!/usr/bin/env python3
"""
cleanup_endpoints.py - Delete deprecated API Gateway endpoints from a report.

Reads a Markdown report produced by report_deprecated.py (which embeds the
deprecation list as JSON), then issues `aws apigateway delete-method` calls
for each entry. Optionally deletes the parent resource when only OPTIONS is
left, and writes a cleanup record so deletions are auditable.

Usage:
    python3 cleanup_endpoints.py --report ./reports/deprecated/dev-bo-2026....md
    python3 cleanup_endpoints.py --report ... --auto       # no per-step prompts
    python3 cleanup_endpoints.py --report ... --dry-run    # preview only

Behaviour notes:
- Always asks for top-level confirmation unless `--auto` or `--dry-run`.
- Does NOT deploy — running scripts mutates only the API definition. After
  cleanup completes, prompt the user to deploy with
  `aws apigateway create-deployment --rest-api-id ID --stage-name STAGE`.
- The cleanup record is written next to the input report.
"""

import argparse
import json
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

JSON_BLOCK_RE = re.compile(
    r"## Datos crudos\s*\n+```json\s*\n(.*?)```",
    re.DOTALL,
)
INFO_RE = re.compile(
    r"\| API Gateway \| `([^`]+)` \(`([^`]+)`\)",
)


def aws_run(command: str, dry_run: bool, description: str) -> Tuple[bool, Dict[str, Any]]:
    """Run an AWS CLI command. Returns (ok, parsed_json_or_empty)."""
    if dry_run:
        print(f"[DRY-RUN] {description}\n         $ {command}")
        return True, {}
    print(f"[EXEC]    {description}")
    result = subprocess.run(
        command, shell=True, capture_output=True, text=True, check=False
    )
    if result.returncode != 0:
        print(
            f"[ERROR]   {description}: {result.stderr.strip()}",
            file=sys.stderr,
        )
        return False, {}
    if not result.stdout.strip():
        return True, {}
    try:
        return True, json.loads(result.stdout)
    except json.JSONDecodeError:
        return True, {}


def parse_report(report_path: Path) -> Tuple[str, str, List[Dict[str, str]]]:
    """Extract (api_name, api_id, deprecated_list) from the report."""
    text = report_path.read_text(encoding="utf-8")
    info = INFO_RE.search(text)
    if not info:
        print(
            "[ERROR] Could not find API metadata line in report.",
            file=sys.stderr,
        )
        sys.exit(1)
    api_name, api_id = info.group(1), info.group(2)

    payload_match = JSON_BLOCK_RE.search(text)
    if not payload_match:
        print(
            "[ERROR] Could not find embedded JSON block. "
            "Make sure the report was generated by report_deprecated.py.",
            file=sys.stderr,
        )
        sys.exit(1)
    deprecated = json.loads(payload_match.group(1))
    return api_name, api_id, deprecated


def get_resource_methods(api_id: str, resource_id: str) -> List[str]:
    """Return method names currently attached to the resource."""
    result = subprocess.run(
        f"aws apigateway get-resource --rest-api-id {api_id} "
        f"--resource-id {resource_id}",
        shell=True, capture_output=True, text=True, check=False,
    )
    if result.returncode != 0:
        return []
    data = json.loads(result.stdout or "{}")
    return list((data.get("resourceMethods") or {}).keys())


def confirm(question: str, default_no: bool = True) -> bool:
    suffix = "[s/N]" if default_no else "[S/n]"
    answer = input(f"{question} {suffix} ").strip().lower()
    if not answer:
        return not default_no
    return answer in {"s", "si", "sí", "y", "yes"}


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Delete deprecated endpoints listed in a report."
    )
    parser.add_argument("--report", required=True, help="Path to the Markdown report.")
    parser.add_argument(
        "--auto", action="store_true",
        help="Skip interactive prompts (still respects --dry-run).",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Print AWS CLI calls instead of running them.",
    )
    parser.add_argument(
        "--remove-orphan-resources", action="store_true",
        help=(
            "After deleting methods, also delete resources that no longer have "
            "any non-OPTIONS methods. Implies cleanup of OPTIONS too."
        ),
    )
    args = parser.parse_args()

    report_path = Path(args.report).expanduser().resolve()
    if not report_path.exists():
        print(f"[ERROR] Report not found: {report_path}", file=sys.stderr)
        return 1

    api_name, api_id, deprecated = parse_report(report_path)
    if not deprecated:
        print("[OK] No deprecated endpoints in report. Nothing to do.")
        return 0

    print(
        f"[INFO] Report has {len(deprecated)} deprecated entries on "
        f"{api_name} ({api_id})."
    )
    for entry in deprecated:
        print(f"  - {entry['method']:6s} {entry['path']}  (resource {entry['resource_id']})")

    if not args.auto and not args.dry_run:
        if not confirm("¿Confirmar eliminación?", default_no=True):
            print("[INFO] Cancelled.")
            return 0

    deleted_methods: List[Dict[str, Any]] = []
    deleted_resources: List[Dict[str, Any]] = []
    failures: List[Dict[str, Any]] = []

    # Group entries per resource so we can decide on cleanup of OPTIONS later.
    by_resource: Dict[str, List[Dict[str, str]]] = {}
    for entry in deprecated:
        by_resource.setdefault(entry["resource_id"], []).append(entry)

    for resource_id, entries in by_resource.items():
        for entry in entries:
            command = (
                f"aws apigateway delete-method "
                f"--rest-api-id {api_id} --resource-id {resource_id} "
                f"--http-method {entry['method']}"
            )
            ok, _ = aws_run(
                command, args.dry_run,
                f"delete-method {entry['method']} {entry['path']}",
            )
            (deleted_methods if ok else failures).append({
                **entry,
                "ok": ok,
            })

        if args.dry_run:
            continue

        if not args.remove_orphan_resources:
            continue

        remaining = [
            m.upper() for m in get_resource_methods(api_id, resource_id)
        ]
        meaningful = [m for m in remaining if m != "OPTIONS"]
        if meaningful:
            continue

        sample = entries[0]
        if not args.auto:
            if not confirm(
                f"Resource `{sample['path']}` ({resource_id}) ya no tiene "
                f"métodos reales. ¿Eliminarlo?",
                default_no=True,
            ):
                continue

        if "OPTIONS" in remaining:
            ok_options, _ = aws_run(
                f"aws apigateway delete-method --rest-api-id {api_id} "
                f"--resource-id {resource_id} --http-method OPTIONS",
                args.dry_run,
                f"delete-method OPTIONS {sample['path']}",
            )
            if not ok_options:
                failures.append({
                    "method": "OPTIONS",
                    "path": sample["path"],
                    "resource_id": resource_id,
                    "ok": False,
                })

        ok_resource, _ = aws_run(
            f"aws apigateway delete-resource --rest-api-id {api_id} "
            f"--resource-id {resource_id}",
            args.dry_run,
            f"delete-resource {sample['path']}",
        )
        target = deleted_resources if ok_resource else failures
        target.append({
            "path": sample["path"],
            "resource_id": resource_id,
            "ok": ok_resource,
        })

    timestamp = datetime.now().strftime("%Y%m%dT%H%M%S")
    cleanup_path = report_path.parent / f"cleanup-{timestamp}.md"
    lines = [
        "# Cleanup de endpoints deprecados",
        "",
        f"- Reporte base: `{report_path.name}`",
        f"- API Gateway: `{api_name}` (`{api_id}`)",
        f"- Fecha: {datetime.now().isoformat()}",
        f"- Modo: {'dry-run' if args.dry_run else ('automático' if args.auto else 'interactivo')}",
        "",
        f"## Métodos eliminados ({len(deleted_methods)})",
        "",
    ]
    if deleted_methods:
        lines.append("| Método | Path | Resource ID | Estado |")
        lines.append("|--------|------|-------------|--------|")
        for entry in deleted_methods:
            mark = "✅" if entry.get("ok") else "❌"
            lines.append(
                f"| {entry['method']} | `{entry['path']}` | "
                f"`{entry['resource_id']}` | {mark} |"
            )
    else:
        lines.append("_(none)_")
    lines.append("")

    lines.append(f"## Recursos eliminados ({len(deleted_resources)})")
    lines.append("")
    if deleted_resources:
        lines.append("| Path | Resource ID | Estado |")
        lines.append("|------|-------------|--------|")
        for entry in deleted_resources:
            mark = "✅" if entry.get("ok") else "❌"
            lines.append(
                f"| `{entry['path']}` | `{entry['resource_id']}` | {mark} |"
            )
    else:
        lines.append("_(none)_")
    lines.append("")

    if failures:
        lines.append(f"## Errores ({len(failures)})")
        lines.append("")
        lines.append("```json")
        lines.append(json.dumps(failures, indent=2))
        lines.append("```")
        lines.append("")

    lines.append("## Próximos pasos")
    lines.append("")
    lines.append(
        "Para que los cambios sean visibles en el stage es necesario un deploy:"
    )
    lines.append("")
    lines.append("```")
    lines.append(
        f"aws apigateway create-deployment --rest-api-id {api_id} "
        f"--stage-name <STAGE> --description \"Cleanup deprecated\""
    )
    lines.append("```")
    cleanup_path.write_text("\n".join(lines), encoding="utf-8")

    print(f"[OK] Cleanup report: {cleanup_path}")
    print(
        f"[OK] Methods deleted: {len(deleted_methods)} | "
        f"Resources deleted: {len(deleted_resources)} | "
        f"Failures: {len(failures)}"
    )
    return 0 if not failures else 2


if __name__ == "__main__":
    sys.exit(main())
